# Generated by Django 2.1 on 2018-10-20 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('template_path', models.CharField(max_length=128)),
                ('seo_title', models.CharField(max_length=64)),
                ('seo_keywords', models.TextField(max_length=128)),
                ('seo_des', models.TextField(max_length=256)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_pub', models.BooleanField(default=True)),
                ('gmt_auto_pub', models.DateTimeField()),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('depth', models.PositiveSmallIntegerField()),
                ('template_path', models.CharField(max_length=128)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_updated', models.DateTimeField(auto_now=True)),
                ('parent_folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_cms_apiw.Folder')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='belong_to_folder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_cms_apiw.Folder'),
        ),
    ]
