# Generated by Django 2.1 on 2018-10-20 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_cms_apiw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.TextField(help_text='文章内容'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(help_text='标题', max_length=64),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_folder_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_cms_apiw.Folder'),
        ),
    ]
